name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        description: Semantic version value
        default: patch
        options:
          - patch
          - minor
          - major

concurrency:
  group: cd-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  release:
    name: Release
    needs:
      - ci
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup
        with:
          fundamentry-token: ${{ secrets.FUNDAMENTRY_BOT_TOKEN }}

      - name: Count changed packages
        id: changes
        run: echo "count=$(pnpx lerna changed -p | wc -l | xargs)" >> "$GITHUB_OUTPUT"

      - name: Import GPG key
        if: ${{ inputs.version || fromJson(steps.changes.outputs.count) > 0 }}
        uses: crazy-max/ghaction-import-gpg@v7
        id: gpg
        with:
          gpg_private_key: ${{ secrets.FUNDAMENTRY_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.FUNDAMENTRY_BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: false # https://github.com/semantic-release/semantic-release/pull/1871

      - name: Automatic release
        if: ${{ !inputs.version && fromJson(steps.changes.outputs.count) > 0 }}
        run: pnpm lerna publish --yes
        env:
          GH_TOKEN: ${{ secrets.FUNDAMENTRY_BOT_TOKEN }}

      - name: Manual release
        if: ${{ inputs.version }}
        run: pnpm lerna publish ${{ inputs.version }} --yes
        env:
          GH_TOKEN: ${{ secrets.FUNDAMENTRY_BOT_TOKEN }}
